title: KGrid Authoring Manual
author: KGrid Development Team
email: dlhs.knowledge.grid@umich.edu
multipage: true
description: > # this means to ignore newlines until "baseurl:"
  This authoring Manual provides a set of basic instructions and guidelines for creating Knowledge Objects


# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# header_pages:
#   - getting_started.md
#   - activator_checklist.md
#   - test_functions.md
#   - commands.md
#   - how_execution_stack_works.md
#   - troubleshooting.md
#   - additional_resources.md


#theme: jekyll-theme-cayman
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
